schema_version = 1
id = '019f5887-e205-715a-8990-ec67a8097cf7'
slug = 'git-update-pr-action'
kind = 'feature'
canonical_branch = 'update-pr-action'
upstreamability = 'independent'
status = 'active'
active_revision_id = '019fa3c2-fd55-7c0f-ab42-a8a829721dd1'
active_intent_revision_id = '019f5887-e205-75e5-84d6-788344c15d45'
created_at = '2026-07-12T22:52:08.069243Z'
